### ISSUE TITLE
Wrong position in android [help needed]

### ISSUE THREAD

**Issue by kamalpandey** [AndreiCalazans/rn-tooltip#5] opened 2018-09-04 10:40 UTC
In android the label appears twice and the tool tip appears at wrong position

**Comment by AndreiCalazans** [comment] 2018-09-05 19:35
@kamalpandey can you post images of what's going on and snippets of your code?

**Comment by mahdidavoodi7** [comment] 2018-09-17 11:14
@AndreiCalazans I think you forgot to consider apps without statusBars
i have the same problem 
and if you want i can send picture for you

**Comment by mahdidavoodi7** [comment] 2018-09-17 19:41
![photo_2018-09-18_00-10-03](https://user-images.githubusercontent.com/29153345/45646002-62048b00-bad7-11e8-9a1a-8d6ba90087aa.jpg)

Here You are @kamalpandey

**Comment by mahdidavoodi7** [comment] 2018-09-17 19:43
@AndreiCalazans 
As you can see i don't have status bar and when i click on that button it make an image of the button 
and i think this is the problem

**Comment by AndreiCalazans** [comment] 2018-09-27 23:54
Closing due to the lack of reproduction as stated on the PR which @mahdidavoodi7 opened. https://github.com/AndreiCalazans/rn-tooltip/pull/6#issuecomment-425277930

Please reopen the ticket with a reproducible app if you are still facing the problem.

**Comment by mahdidavoodi7** [comment] 2018-09-29 19:09
hey man 
i dont know where is the problem but still i have this problem 
`
<View style={viewStyle}>
            <StatusBar hidden = {true}/>
            <View style={{marginLeft:15,alignSelf:'center'}}>
                <Tooltip noStatusBar={true} popover={<Text>Info here</Text>}>
                    <Ionicons name='question-circle-o' size={25} />
                </Tooltip>
            </View>
                  <Text style={textStyle}>{props.children}</Text>
                 <Ionicons2 size={25} style={{marginRight:15,alignSelf:'center'}}/>
            </View>
`
this code is for my header and i want tooltip when question button clicked but i got wrong position of tooltip as you can see in the attached picture 
![45646002-62048b00-bad7-11e8-9a1a-8d6ba90087aa](https://user-images.githubusercontent.com/29153345/46249555-f6f07800-c437-11e8-84e7-a268248e3dca.jpg)

**Comment by AndreiCalazans** [comment] 2018-09-29 20:08
@mahdidavoodi7 I can't help you with just what you are providing. Please provide a complete example of the problem you are facing and with full screenshot.


Here is an example with what you are trying to accomplish


<img width="250" alt="IconInHeader" src="https://user-images.githubusercontent.com/20777666/46250100-0eb10780-c40a-11e8-9246-b8f5e9b9ff72.gif">

**The code**

```JavaScript
const Header = (props) => 
  <View style={{ height: 80, backgroundColor: 'lightgray' }} justifyContent='center'>
    {props.children}
  </View>

const Body = (props) => 
  <View flex={1} backgroundColor='lightblue'>
    {props.children}
  </View>;

export default class App extends Component<Props> {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <StatusBar hidden={true} />
        <Header>
          <View style={{ height: 25, width: 25, justifyContet: 'center', backgroundColor: 'darkgray', marginLeft: 25 }}>
            <Tooltip popover={<Text>Info here</Text>}>
              <Text style={{ height: 25, width: 25 }}>ICO</Text>
            </Tooltip>
          </View>
        </Header>
        <Body>
          {this.props.children}
        </Body>
      </View>
    );
  }
}

```

**Comment by mahdidavoodi7** [comment] 2018-09-30 13:47
Can i use icon in tooltip beside text ???

**Comment by AndreiCalazans** [comment] 2018-10-01 11:42
You should be able to.

**Comment by Yevpak** [comment] 2019-01-16 14:00
Hello
i have the same problem on Android

**Comment by ahsanjamilarkhitech** [comment] 2019-09-25 10:39
same problem in android

**Comment by ahsanjamilarkhitech** [comment] 2019-09-25 11:44
I am having same issue on android

**Comment by AndreiCalazans** [comment] 2019-09-25 12:26
If you can provide an example preferably using Expo Snack I can try to help.

**Closed by AndreiCalazans** 2019-09-25 12:26 UTC
Labels: invalid

**Comment by ahsanjamilarkhitech** [comment] 2019-09-25 12:31
Thanks, resolved thanks to this:
https://github.com/react-native-training/react-native-elements/issues/1871#issuecomment-485255900

**Comment by hugumberto** [comment] 2021-02-06 19:19
@AndreiCalazans, here you can find a snack of the problem
https://snack.expo.io/jFUSrugg4
![image](https://user-images.githubusercontent.com/4248940/107127764-47056200-68b0-11eb-9a49-9e4f964ac8b3.png)

**Comment by AndreiCalazans** [comment] 2021-02-08 13:52
Wrapping the Toolltip JSX with a container can help

```
return (
    <View style={styles.container}>
      <TextInput placeholder='click me first'></TextInput>
      <View style={{ width: "50%", height: 30, backgroundColor: 'yellow' }}>
        <Tooltip popover={<Text>Info here</Text>}>
          <Text>click me second</Text>
        </Tooltip>
      </View>
    </View>
  );

```
